// <auto-generated />
using System;
using Hostify.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hostify.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240922081913_refact-reservation-table")]
    partial class refactreservationtable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hostify.Models.Quarto", b =>
                {
                    b.Property<int>("IdQuarto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdQuarto"));

                    b.Property<int>("HotelIdUtilizador")
                        .HasColumnType("integer");

                    b.Property<int>("QuartoCapacidade")
                        .HasColumnType("integer");

                    b.Property<string>("QuartoDescricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuartoDiaria")
                        .HasColumnType("numeric");

                    b.Property<bool>("QuartoDisponivel")
                        .HasColumnType("boolean");

                    b.Property<string>("QuartoImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuartoLocalizacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuartoTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdQuarto");

                    b.HasIndex("HotelIdUtilizador");

                    b.ToTable("Quarto");
                });

            modelBuilder.Entity("Hostify.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("DescriptionReserva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FimReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InicioReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TypeReserva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("hospedeIdUtilizador")
                        .HasColumnType("integer");

                    b.Property<int>("hotelIdUtilizador")
                        .HasColumnType("integer");

                    b.Property<int>("quartoIdQuarto")
                        .HasColumnType("integer");

                    b.HasKey("IdReserva");

                    b.HasIndex("hospedeIdUtilizador");

                    b.HasIndex("hotelIdUtilizador");

                    b.HasIndex("quartoIdQuarto");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Hostify.Models.Utilizador", b =>
                {
                    b.Property<int>("IdUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilizador"));

                    b.Property<string>("EmailUtilizador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameUtilizador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordUtilizador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneUtilizador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeUtilizador")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("UsernameUtilizador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUtilizador");

                    b.HasIndex("UsernameUtilizador")
                        .IsUnique();

                    b.ToTable("Utilizador");

                    b.HasDiscriminator<string>("TypeUtilizador").HasValue("Utilizador");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hostify.Models.Hospede", b =>
                {
                    b.HasBaseType("Hostify.Models.Utilizador");

                    b.HasDiscriminator().HasValue("Hospede");
                });

            modelBuilder.Entity("Hostify.Models.Hotel", b =>
                {
                    b.HasBaseType("Hostify.Models.Utilizador");

                    b.HasDiscriminator().HasValue("Hotel");
                });

            modelBuilder.Entity("Hostify.Models.Quarto", b =>
                {
                    b.HasOne("Hostify.Models.Hotel", "Hotel")
                        .WithMany()
                        .HasForeignKey("HotelIdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Hostify.Models.Reserva", b =>
                {
                    b.HasOne("Hostify.Models.Hospede", "hospede")
                        .WithMany()
                        .HasForeignKey("hospedeIdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hostify.Models.Hotel", "hotel")
                        .WithMany()
                        .HasForeignKey("hotelIdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hostify.Models.Quarto", "quarto")
                        .WithMany()
                        .HasForeignKey("quartoIdQuarto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hospede");

                    b.Navigation("hotel");

                    b.Navigation("quarto");
                });
#pragma warning restore 612, 618
        }
    }
}
